### ISSUE TITLE
Trouble installing on Ubuntu 12.04

### ISSUE THREAD

**Issue by ccrean** [manufactured-solutions/MASA#33]
I'm seeing the following error message when I do 'make install':

/usr/bin/install -c -m 644 ../src/masa.mod /usr/local/lib/masa.mod
/usr/bin/install: cannot stat `../src/masa.mod': No such file or directory
make[3]: *** [install-data-local] Error 1
make[3]: Leaving directory `/home/cory/Downloads/MASA/src'
make[2]: *** [install-am] Error 2
make[2]: Leaving directory `/home/cory/Downloads/MASA/src'
make[1]: *** [install] Error 2
make[1]: Leaving directory `/home/cory/Downloads/MASA/src'
make: *** [install-recursive] Error 1

I'm using Ubuntu 12.04, gcc 4.6.3, MASA 0.50.0, and my configure line was just './configure'.

**Comment by nicholasmalaya** [comment]
I was able to reproduce your error locally. Hash d26ea86, I believe, provides the necessary fixes to the Makefile.AM.  However, I cannot completely reproduce your environment. Would you try this with the latest patch and see if things are working properly?

I would recommend, 
'git pull' to grab the latest code from master followed by a new boostrap,configure, make, make install. 
Also, you might consider a local install directory using prefix, e.g. ./configure --prefix=/place/to/install, otherwise your make install will be placing the libraries in /bin/

**Comment by ccrean** [comment]
That worked!  Thank you!

**Comment by nicholasmalaya** [comment]
Great! Hope it is smooth sailing for here on out.
